title = "openBVE"
theme = "openbve"
DefaultContentLanguage = "en"
defaultContentLanguageInSubdir = true
removePathAccents = true

relativeURLs = true
uglyURLs = true

disableKinds = ["page", "404", "taxonomy", "taxonomyTerm", "RSS", "sitemap"]

[blackfriday]
  hrefTargetBlank = true
  extensions = ["laxHtmlBlocks"]

[languages]
[languages.en]
contentDir = "content/en"
languageName = "English"
weight = 1
[languages.ja]
contentDir = "content/ja"
languageName = "日本語"
weight = 2
